# Generated by Django 5.2.1 on 2025-05-16 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('serie', 'Serie'), ('pelicula', 'Película')], max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('duracion', models.PositiveIntegerField(blank=True, help_text='Duración en minutos', null=True)),
                ('idioma', models.CharField(blank=True, max_length=50)),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('video_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categoria')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contenido')),
            ],
        ),
        migrations.AddField(
            model_name='contenido',
            name='categorias',
            field=models.ManyToManyField(related_name='contenidos', through='myapp.ContenidoCategoria', to='myapp.categoria'),
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.PositiveIntegerField()),
                ('numero_episodio', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('video_url', models.URLField()),
                ('serie', models.ForeignKey(limit_choices_to={'tipo': 'serie'}, on_delete=django.db.models.deletion.CASCADE, to='myapp.contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('tipo', models.CharField(choices=[('adulto', 'Adulto'), ('infantil', 'Infantil')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialReproduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_reproducido', models.PositiveIntegerField(help_text='Segundos')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contenido')),
                ('episodio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.episodio')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contenido')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contenido')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.perfil')),
            ],
        ),
    ]
