# Generated by Django 5.2.1 on 2025-05-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
