# Generated by Django 5.2.1 on 2025-05-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_perfil_avatar_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='video_url',
            field=models.URLField(max_length=1000),
        ),
    ]
