# Generated by Django 5.2.1 on 2025-05-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_episodio_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
