# Generated by Django 5.2.1 on 2025-05-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_contenido_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
