# Generated by Django 5.2.1 on 2025-05-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_episodio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
