# Generated by Django 5.2.1 on 2025-06-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_episodio_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='contenido',
            options={'ordering': ['-año', '-id']},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='año',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='tipo',
            field=models.CharField(choices=[('serie', 'Serie'), ('pelicula', 'Película')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='titulo',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='contenido',
            index=models.Index(fields=['titulo', 'tipo'], name='myapp_conte_titulo_30d23f_idx'),
        ),
        migrations.AddIndex(
            model_name='contenido',
            index=models.Index(fields=['año', '-id'], name='myapp_conte_año_b1f3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='contenido',
            index=models.Index(fields=['tipo', 'año'], name='myapp_conte_tipo_32775b_idx'),
        ),
    ]
