# Generated by Django 5.2.1 on 2025-06-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_categoria_options_alter_contenido_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveIndex(
            model_name='contenido',
            name='myapp_conte_tipo_32775b_idx',
        ),
        migrations.AddIndex(
            model_name='contenido',
            index=models.Index(fields=['-id'], name='myapp_conte_id_984d06_idx'),
        ),
    ]
