# Generated by Django 5.2 on 2025-06-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_contenido_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodio',
            name='video_file',
            field=models.FileField(blank=True, help_text='Archivo de video local', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL externa (S3, CDN u otro almacenamiento)', max_length=1000, null=True),
        ),
    ]
