# Generated by Django 5.2.1 on 2025-06-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_episodio_video_file_alter_episodio_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
