# Generated by Django 5.2.1 on 2025-06-14 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_comentario_comentario_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentario',
            new_name='Calificacion',
        ),
    ]
