# Generated by Django 5.2.1 on 2025-06-14 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_comentario_calificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='comentario',
        ),
    ]
