# Generated by Django 5.2.1 on 2025-06-14 07:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_accesofallido_auditlog_sesionusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termino_busqueda', models.CharField(db_index=True, max_length=255)),
                ('termino_normalizado', models.CharField(db_index=True, help_text='Término en minúsculas y sin espacios extra', max_length=255)),
                ('resultados_encontrados', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.perfil')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Búsqueda',
                'verbose_name_plural': 'Historial de Búsquedas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['termino_normalizado', 'timestamp'], name='myapp_histo_termino_2279af_idx'), models.Index(fields=['usuario', 'timestamp'], name='myapp_histo_usuario_bdd93a_idx'), models.Index(fields=['timestamp'], name='myapp_histo_timesta_687b7a_idx'), models.Index(fields=['termino_normalizado', '-timestamp'], name='myapp_histo_termino_1631e0_idx')],
            },
        ),
    ]
