# Generated by Django 5.2.1 on 2025-06-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_historialbusqueda'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='anilist_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='anilist_popularity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='anilist_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='anilist_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contenido',
            name='fecha_importacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
