# Generated by Django 5.2 on 2025-07-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_contenido_anilist_id_contenido_anilist_popularity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
